SRCS = image.c \
       palette.c \
       random.c \
       grlib.c \
       font.c \
       filter.c 

OBJS = $(SRCS:.c=.o)

TLIB = ../lib/libfilter.a

include ../dos.mak
CFLAGS=$(CFLAGS1) -I ../include

all:	$(TLIB)

$(TLIB):$(OBJS)
	rm -f $@
	$(AR) rc $@ $^

clean:
	rm -f $(TLIB)
	rm -f *.[oas]
	rm -f *~
	rm -f core 

distclean:clean

ctrl87.o:
	$(CC) ctrl87.c -c

