SRCS = ui_aa.c \

OBJS = $(SRCS:.c=.o)

include ../../../dos.mak
CFLAGS=$(CFLAGS1) -I ../../../include

TLIB = ../../../lib/libuiaa.a


all:	$(TLIB)

$(TLIB):$(OBJS)
	rm -f $@
	$(AR) rc $@ $^

clean:
	rm -f $(TLIB)
	rm -f *.[oas]
	rm -f *~
	rm -f core 

distclean:clean

#dep:
	#rm -f .depend
	#make .depend
#
#.depend:
	#echo '# Program dependencies' >.depend
	#gcc -I svgalib $(DEFINES) -MM $(patsubst %.o,%.c,$(OBJS)) >>.depend
#
#include depend

