 o	New text.c Support for text output primitives
 o	New wstack.c - support for simple windows
 o	New playtext.c for displaying messages
 o	font moved from os2 drivers to ui. (takk: please fix this in yur
		 driver)
 o	Image now allows to define few color cells for UI, wich are allocated at the
 	begining of palette
 o	Updated all drivers to support new prealocating (palette handling functions needs
        to know palette now)
 o	Removed curses driver (aa driver will need some hacking for new text output
		 stuff in order to make it useable, and I don't want to make such
		 dirty hacks twice. Also curses driver had quite old rendering code
		 and some functions was broken)
 o	New message and error handling code in ui library
 o	Changes text displaying/saving code
 o	Clear screen is now handled in ui_helper instead of uinew
 o	Changed ministatus/status code to use new windowing and text primitives
 o	Dialog can now be generated by called function. Usefull for setting default values
