  o GGI driver
  o Cleanups into driver's API
  o Improved handling of checkboxed dialoged functions...
  o Fixed some bugs in menu printing and syntax a bit
    (sorry Rodo...:)
    now it prints radio/checkbox 
    in radio/checkbox it print on/off flag too
  o Short names of incolorings and such..
  o New print_menu and print_dialog commands
  o Fixes for plan9...
  o better waitcursor handling...
