#!/bin/sh
processline()
{
	file=$1
	echo "- $file -"
	>tempfile
	shift
	while [ "$1" != "" ]; do
		echo ".. _$1:" >> tempfile
		shift
	done
	echo >> tempfile
	cat $file >> tempfile
	mv tempfile $file
}

process()
{
        while read line ; do
                eval "processline $line"
        done
}
cat anchors | process
