s!\[help:main\]!help:anchor=main bookID=XaoS Help!g
s!\[help:about\]!help:anchor=about bookID=XaoS Help!g
s!\[help:start\]!help:anchor=start bookID=XaoS Help!g
s!\[help:support\]!help:anchor=support bookID=XaoS Help!g
s!\[help:devel\]!help:anchor=devel bookID=XaoS Help!g
s!\[help:sffe\]!help:anchor=sffe bookID=XaoS Help!g
s!\[help:usrform\]!help:anchor=sffe bookID=XaoS Help!g
s!\[help:usrformInit\]!help:anchor=sffe bookID=XaoS Help!g
s!\[help:video\]!help:anchor=video bookID=XaoS Help!g
s!\[help:berkeley\]!help:anchor=berkeley bookID=XaoS Help!g
s!\[help:controls\]!help:anchor=controls bookID=XaoS Help!g
s!\[help:writehelp\]!help:anchor=writehelp bookID=XaoS Help!g
s!\[help:xshl\]!help:anchor=xshl bookID=XaoS Help!g
s!\[help:format\]!help:anchor=format bookID=XaoS Help!g
s!\[help:drivers\]!help:anchor=drivers bookID=XaoS Help!g
s!\[help:cocoa\]!help:anchor=cocoa bookID=XaoS Help!g
s!\[help:aa\]!help:anchor=aa bookID=XaoS Help!g
s!\[help:dos\]!help:anchor=dos bookID=XaoS Help!g
s!\[help:ggi\]!help:anchor=ggi bookID=XaoS Help!g
s!\[help:plan9\]!help:anchor=plan9 bookID=XaoS Help!g
s!\[help:SVGAlib\]!help:anchor=SVGAlib bookID=XaoS Help!g
s!\[help:win32\]!help:anchor=win32 bookID=XaoS Help!g
s!\[help:dX-window\]!help:anchor=dX-window bookID=XaoS Help!g
s!\[help:dX-fullscreen\]!help:anchor=dX-fullscreen bookID=XaoS Help!g
s!\[help:BeOS\]!help:anchor=BeOS bookID=XaoS Help!g
s!\[help:DirectWindow\]!help:anchor=BeOS bookID=XaoS Help!g
s!\[help:WindowScreen\]!help:anchor=BeOS bookID=XaoS Help!g
s!\[help:X11\]!help:anchor=X11 bookID=XaoS Help!g
s!\[help:DGA\]!help:anchor=DGA bookID=XaoS Help!g
s!\[help:tutorial\]!help:anchor=tutorial bookID=XaoS Help!g
s!\[help:menus\]!help:anchor=menus bookID=XaoS Help!g
s!\[help:end\]!help:anchor=end bookID=XaoS Help!g
s!\[help:root\]!help:anchor=root bookID=XaoS Help!g
s!\[help:animroot\]!help:anchor=animroot bookID=XaoS Help!g
s!\[help:stopreplay\]!help:anchor=stopreplay bookID=XaoS Help!g
s!\[help:plc\]!help:anchor=plc bookID=XaoS Help!g
s!\[help:load\]!help:anchor=load bookID=XaoS Help!g
s!\[help:linemenu\]!help:anchor=linemenu bookID=XaoS Help!g
s!\[help:line\]!help:anchor=line bookID=XaoS Help!g
s!\[help:morphline\]!help:anchor=morphline bookID=XaoS Help!g
s!\[help:morphlastline\]!help:anchor=morphlastline bookID=XaoS Help!g
s!\[help:linekey\]!help:anchor=linekey bookID=XaoS Help!g
s!\[help:clearline\]!help:anchor=clearline bookID=XaoS Help!g
s!\[help:clearlines\]!help:anchor=clearlines bookID=XaoS Help!g
s!\[help:animf\]!help:anchor=animf bookID=XaoS Help!g
s!\[help:animateview\]!help:anchor=animateview bookID=XaoS Help!g
s!\[help:smoothmorph\]!help:anchor=smoothmorph bookID=XaoS Help!g
s!\[help:morphview\]!help:anchor=morphview bookID=XaoS Help!g
s!\[help:morphjulia\]!help:anchor=morphjulia bookID=XaoS Help!g
s!\[help:moveview\]!help:anchor=moveview bookID=XaoS Help!g
s!\[help:morphangle\]!help:anchor=morphangle bookID=XaoS Help!g
s!\[help:zoom\]!help:anchor=zoom bookID=XaoS Help!g
s!\[help:zoom\]!help:anchor=zoom bookID=XaoS Help!g
s!\[help:unzoom\]!help:anchor=zoom bookID=XaoS Help!g
s!\[help:stop\]!help:anchor=zoom bookID=XaoS Help!g
s!\[help:time\]!help:anchor=time bookID=XaoS Help!g
s!\[help:usleep\]!help:anchor=usleep bookID=XaoS Help!g
s!\[help:textsleep\]!help:anchor=textsleep bookID=XaoS Help!g
s!\[help:wait\]!help:anchor=wait bookID=XaoS Help!g
s!\[help:file\]!help:anchor=file bookID=XaoS Help!g
s!\[help:loadpos\]!help:anchor=loadpos bookID=XaoS Help!g
s!\[help:savepos\]!help:anchor=savepos bookID=XaoS Help!g
s!\[help:record\]!help:anchor=record bookID=XaoS Help!g
s!\[help:play\]!help:anchor=play bookID=XaoS Help!g
s!\[help:saveimg\]!help:anchor=saveimg bookID=XaoS Help!g
s!\[help:loadexample\]!help:anchor=loadexample bookID=XaoS Help!g
s!\[help:savecfg\]!help:anchor=savecfg bookID=XaoS Help!g
s!\[help:quit\]!help:anchor=quit bookID=XaoS Help!g
s!\[help:quitmenu\]!help:anchor=quit bookID=XaoS Help!g
s!\[help:noquit\]!help:anchor=quit bookID=XaoS Help!g
s!\[help:edit\]!help:anchor=edit bookID=XaoS Help!g
s!\[help:undo\]!help:anchor=undo bookID=XaoS Help!g
s!\[help:redo\]!help:anchor=redo bookID=XaoS Help!g
s!\[help:copy\]!help:anchor=copy bookID=XaoS Help!g
s!\[help:paste\]!help:anchor=paste bookID=XaoS Help!g
s!\[help:fractal\]!help:anchor=fractal bookID=XaoS Help!g
s!\[help:formula\]!help:anchor=formula bookID=XaoS Help!g
s!\[help:uimandelbrot\]!help:anchor=uimandelbrot bookID=XaoS Help!g
s!\[help:julia\]!help:anchor=uimandelbrot bookID=XaoS Help!g
s!\[help:juliaseed\]!help:anchor=uimandelbrot bookID=XaoS Help!g
s!\[help:uiperturbation\]!help:anchor=uiperturbation bookID=XaoS Help!g
s!\[help:perturbation\]!help:anchor=uiperturbation bookID=XaoS Help!g
s!\[help:bailout\]!help:anchor=bailout bookID=XaoS Help!g
s!\[help:bailout\]!help:anchor=bailout bookID=XaoS Help!g
s!\[help:uiview\]!help:anchor=uiview bookID=XaoS Help!g
s!\[help:view\]!help:anchor=uiview bookID=XaoS Help!g
s!\[help:angle\]!help:anchor=uiview bookID=XaoS Help!g
s!\[help:initstate\]!help:anchor=initstate bookID=XaoS Help!g
s!\[help:plane\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:mplane\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:plane0\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:plane1\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:plane2\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:plane3\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:plane4\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:plane5\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:plane6\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:plane7\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:plane8\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:plane9\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:plane10\]!help:anchor=plane bookID=XaoS Help!g
s!\[help:incoloring\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:mincoloring\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:in1\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:in2\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:in3\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:in4\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:in5\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:in6\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:in7\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:in8\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:in9\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:in10\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:in0\]!help:anchor=incoloring bookID=XaoS Help!g
s!\[help:outcoloring\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:moutcoloring\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:out1\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:out2\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:out3\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:out4\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:out5\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:out6\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:out7\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:out8\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:out9\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:out10\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:out0\]!help:anchor=outcoloring bookID=XaoS Help!g
s!\[help:tcolor\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:intcoloring\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outtcoloring\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:tincoloring\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:toucoloring\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int0\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int1\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int2\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int3\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int4\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int5\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int6\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int7\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int8\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int9\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int10\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:int11\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt0\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt1\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt2\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt3\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt4\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt5\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt6\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt7\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt8\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt9\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt10\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:outt11\]!help:anchor=tcolor bookID=XaoS Help!g
s!\[help:calc\]!help:anchor=calc bookID=XaoS Help!g
s!\[help:range\]!help:anchor=range bookID=XaoS Help!g
s!\[help:mguess\]!help:anchor=range bookID=XaoS Help!g
s!\[help:guess0\]!help:anchor=range bookID=XaoS Help!g
s!\[help:guess1\]!help:anchor=range bookID=XaoS Help!g
s!\[help:guess2\]!help:anchor=range bookID=XaoS Help!g
s!\[help:guess3\]!help:anchor=range bookID=XaoS Help!g
s!\[help:guess4\]!help:anchor=range bookID=XaoS Help!g
s!\[help:guess5\]!help:anchor=range bookID=XaoS Help!g
s!\[help:guess6\]!help:anchor=range bookID=XaoS Help!g
s!\[help:guess7\]!help:anchor=range bookID=XaoS Help!g
s!\[help:guess8\]!help:anchor=range bookID=XaoS Help!g
s!\[help:guess9\]!help:anchor=range bookID=XaoS Help!g
s!\[help:guessall\]!help:anchor=range bookID=XaoS Help!g
s!\[help:periodicity\]!help:anchor=periodicity bookID=XaoS Help!g
s!\[help:maxiter\]!help:anchor=maxiter bookID=XaoS Help!g
s!\[help:fastjulia\]!help:anchor=fastjulia bookID=XaoS Help!g
s!\[help:dynamic\]!help:anchor=dynamic bookID=XaoS Help!g
s!\[help:nodynamic\]!help:anchor=dynamic bookID=XaoS Help!g
s!\[help:dynamicanimation\]!help:anchor=dynamic bookID=XaoS Help!g
s!\[help:dynamicnew\]!help:anchor=dynamic bookID=XaoS Help!g
s!\[help:fastmode\]!help:anchor=dynamic bookID=XaoS Help!g
s!\[help:rotate\]!help:anchor=rotate bookID=XaoS Help!g
s!\[help:norotate\]!help:anchor=rotate bookID=XaoS Help!g
s!\[help:controtate\]!help:anchor=rotate bookID=XaoS Help!g
s!\[help:mouserotate\]!help:anchor=rotate bookID=XaoS Help!g
s!\[help:rotationspeed\]!help:anchor=rotate bookID=XaoS Help!g
s!\[help:autorotate\]!help:anchor=rotate bookID=XaoS Help!g
s!\[help:fastrotate\]!help:anchor=rotate bookID=XaoS Help!g
s!\[help:mfilter\]!help:anchor=mfilter bookID=XaoS Help!g
s!\[help:filter\]!help:anchor=filter bookID=XaoS Help!g
s!\[help:edge\]!help:anchor=edge bookID=XaoS Help!g
s!\[help:edge2\]!help:anchor=edge2 bookID=XaoS Help!g
s!\[help:starfield\]!help:anchor=starfield bookID=XaoS Help!g
s!\[help:stereogram\]!help:anchor=stereogram bookID=XaoS Help!g
s!\[help:interlace\]!help:anchor=interlace bookID=XaoS Help!g
s!\[help:blur\]!help:anchor=blur bookID=XaoS Help!g
s!\[help:emboss\]!help:anchor=emboss bookID=XaoS Help!g
s!\[help:palettef\]!help:anchor=palettef bookID=XaoS Help!g
s!\[help:anti\]!help:anchor=anti bookID=XaoS Help!g
s!\[help:truecolor\]!help:anchor=truecolor bookID=XaoS Help!g
s!\[help:ui\]!help:anchor=ui bookID=XaoS Help!g
s!\[help:uia\]!help:anchor=ui bookID=XaoS Help!g
s!\[help:speed\]!help:anchor=speed bookID=XaoS Help!g
s!\[help:speedup\]!help:anchor=speed bookID=XaoS Help!g
s!\[help:maxstep\]!help:anchor=speed bookID=XaoS Help!g
s!\[help:letterspersec\]!help:anchor=letterspersec bookID=XaoS Help!g
s!\[help:animletterspersec\]!help:anchor=letterspersec bookID=XaoS Help!g
s!\[help:autopilot\]!help:anchor=autopilot bookID=XaoS Help!g
s!\[help:recalculate\]!help:anchor=recalculate bookID=XaoS Help!g
s!\[help:interrupt\]!help:anchor=interrupt bookID=XaoS Help!g
s!\[help:animinterrupt\]!help:anchor=interrupt bookID=XaoS Help!g
s!\[help:nogui\]!help:anchor=nogui bookID=XaoS Help!g
s!\[help:status\]!help:anchor=status bookID=XaoS Help!g
s!\[help:animstatus\]!help:anchor=status bookID=XaoS Help!g
s!\[help:ministatus\]!help:anchor=ministatus bookID=XaoS Help!g
s!\[help:animministatus\]!help:anchor=ministatus bookID=XaoS Help!g
s!\[help:misc\]!help:anchor=misc bookID=XaoS Help!g
s!\[help:command\]!help:anchor=command bookID=XaoS Help!g
s!\[help:renderanim\]!help:anchor=renderanim bookID=XaoS Help!g
s!\[help:clearscreen\]!help:anchor=clearscreen bookID=XaoS Help!g
s!\[help:display\]!help:anchor=display bookID=XaoS Help!g
s!\[help:text\]!help:anchor=text bookID=XaoS Help!g
s!\[help:color\]!help:anchor=color bookID=XaoS Help!g
s!\[help:textposition\]!help:anchor=textposition bookID=XaoS Help!g
s!\[help:message\]!help:anchor=message bookID=XaoS Help!g
s!\[help:helpmenu\]!help:anchor=helpmenu bookID=XaoS Help!g
s!\[help:help\]!help:anchor=help bookID=XaoS Help!g
s!\[help:xtextpos\]!help:anchor=xtextpos bookID=XaoS Help!g
s!\[help:xtextleft\]!help:anchor=xtextleft bookID=XaoS Help!g
s!\[help:xtextcenter\]!help:anchor=xtextcenter bookID=XaoS Help!g
s!\[help:xtexteight\]!help:anchor=xtexteight bookID=XaoS Help!g
s!\[help:ytextpos\]!help:anchor=ytextpos bookID=XaoS Help!g
s!\[help:ytextup\]!help:anchor=ytextup bookID=XaoS Help!g
s!\[help:ytextmiddle\]!help:anchor=ytextmiddle bookID=XaoS Help!g
s!\[help:ytextbottom\]!help:anchor=ytextbottom bookID=XaoS Help!g
s!\[help:mformula\]!help:anchor=mformula bookID=XaoS Help!g
s!\[help:mandel\]!help:anchor=mandel bookID=XaoS Help!g
s!\[help:mandel3\]!help:anchor=mandel3 bookID=XaoS Help!g
s!\[help:mandel4\]!help:anchor=mandel3 bookID=XaoS Help!g
s!\[help:mandel5\]!help:anchor=mandel3 bookID=XaoS Help!g
s!\[help:mandel6\]!help:anchor=mandel3 bookID=XaoS Help!g
s!\[help:octal\]!help:anchor=octal bookID=XaoS Help!g
s!\[help:newton\]!help:anchor=newton bookID=XaoS Help!g
s!\[help:barnsley\]!help:anchor=barnsley bookID=XaoS Help!g
s!\[help:phoenix\]!help:anchor=phoenix bookID=XaoS Help!g
s!\[help:magnet\]!help:anchor=magnet bookID=XaoS Help!g
s!\[help:palettemenu\]!help:anchor=palettemenu bookID=XaoS Help!g
s!\[help:defpalette\]!help:anchor=defpalette bookID=XaoS Help!g
s!\[help:randompalette\]!help:anchor=randompalette bookID=XaoS Help!g
s!\[help:palette\]!help:anchor=palette bookID=XaoS Help!g
s!\[help:cycling\]!help:anchor=cycling bookID=XaoS Help!g
s!\[help:rcycling\]!help:anchor=cycling bookID=XaoS Help!g
s!\[help:cyclingspeed\]!help:anchor=cycling bookID=XaoS Help!g
s!\[help:shiftpalette\]!help:anchor=shiftpalette bookID=XaoS Help!g
s!\[help:fshift\]!help:anchor=shiftpalette bookID=XaoS Help!g
s!\[help:bshift\]!help:anchor=shiftpalette bookID=XaoS Help!g
s!\[help:endmenus\]!help:anchor=endmenus bookID=XaoS Help!g
s!\[help:gpl\]!help:anchor=gpl bookID=XaoS Help!g
s!\[help:end\]!help:anchor=end bookID=XaoS Help!g
