.TH XaoS 6 "22 Feb 2006" "XaoS" "Demos"

.SH NAME
xaos - Fast interactive real-time fractal zoomer/morpher

.SH DETAILS
This manual page is obsolete and no longer maintained.
Please read the full documentation running
XaoS. You can start it typing 'xaos'. (Press 'h' 3
times to get into the help system.)
.P
In addition,
.B xaos --help
should give a detailed list about the command line options.
