#!/bin/bash
# Creates or updates ChangeLog file. Only for developers.

# We assume that CVS_RSH is already set (export CVS_RSH=ssh)
# and we are in a CVS downloaded directory of XaoS.

cd ..
rcs2log | sed s/"\/cvsroot\/xaos\/XaoS\/"/""/g > ChangeLog
cvs commit -m "Automatic update by mkChangeLog" ChangeLog
