#!/bin/sh
# Creates a recent tarball.
# Assumes that the directory name is XaoS/tools where we currently are.
# Be careful: this script will delete files without asking questions!

NAME=XaoS-3.4pre1

test -x tarball || exit 1 # Sorry, this script should be run inside its directory.

cd ..
make clean
make distclean
rm -fR autom4te.cache
cd ..
rm -fR /tmp/XaoS /tmp/$NAME /tmp/$NAME.tar.gz
cp -a XaoS /tmp
cd /tmp
mv XaoS $NAME
cd $NAME
find -name CVS | xargs rm -fR
cd ..
tar czf $NAME.tar.gz $NAME
